Prepare the dataset

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
import os
os.chdir('/content/drive/MyDrive/aiproject_team11/preprocessing_3')
os.getcwd()

'/content/drive/MyDrive/aiproject_team11/preprocessing_3'

In [14]:
import math
import numpy as np
import pandas as pd
from calendar import monthrange
from sklearn.preprocessing import MinMaxScaler

In [15]:
ds = pd.read_csv('./data_by_states_20230518.csv')
ds

,ID,state,temperature_avg,CDD,GDD,HDD,temperature_max,temperature_min,precipitation,snow_depth,snow_fall,sunlight_svm,sunlight_reg,crop,productions_spring,harvested_spring,cultivated_spring,productions_winter,harvested_winter,cultivated_winter
0,1900-01,AR,44.3,0.0,54.0,634.0,69.0,13.0,2.61,1.000000,3.032499,144.000000,144.000000,Rice,421763.145486,325571.428571,325571.428571,NaN,NaN,NaN
1,1900-02,AR,40.6,0.0,24.0,676.0,72.0,5.0,4.46,0.956964,0.100000,122.000000,122.000000,Rice,421763.145486,325571.428571,325571.428571,NaN,NaN,NaN
2,1900-03,AR,52.4,7.0,166.0,392.0,86.0,22.0,1.23,0.674807,0.966744,194.000000,194.000000,Rice,421763.145486,325571.428571,325571.428571,NaN,NaN,NaN
3,1900-04,AR,63.4,66.0,418.0,108.0,86.0,33.0,3.51,0.000000,0.000000,204.000000,204.000000,Rice,421763.145486,325571.428571,325571.428571,NaN,NaN,NaN
4,1900-05,AR,70.3,186.0,637.0,14.0,88.0,44.0,4.11,0.000000,0.000000,291.000000,291.000000,Rice,421763.145486,325571.428571,325571.428571,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13279,2022-08,SD,71.4,217.0,673.0,9.0,98.0,48.0,1.59,0.000000,0.000000,318.075706,342.089693,Wheat,700388.208000,19694.664000,26358.696000,1033119.36,730000.0,830000.0
13280,2022-09,SD,64.3,92.0,435.0,107.0,95.0,31.0,0.11,0.000000,0.000000,251.065685,277.714613,Wheat,700388.208000,19694.664000,26358.696000,1033119.36,730000.0,830000.0
13281,2022-10,SD,48.1,5.0,104.0,522.0,82.0,13.0,0.10,0.000000,1.000238,215.873366,221.266503,Wheat,700388.208000,19694.664000,26358.696000,1033119.36,730000.0,830000.0
13282,2022-11,SD,28.3,0.0,11.0,1095.0,75.0,5.0,0.68,2.000000,3.300000,156.850476,145.225388,Wheat,700388.208000,19694.664000,26358.696000,1033119.36,730000.0,830000.0
13283,2022-12,SD,11.2,0.0,0.0,1660.0,42.0,-20.0,1.45,10.000000,16.900000,137.932753,153.739515,Wheat,700388.208000,19694.664000,26358.696000,1033119.36,730000.0,830000.0

In [16]:
da = pd.read_csv('./data_by_all_20230518.csv')
da

,ID,fertilizer_price_index_all,fertilizer_price_index_nitrogen,fertilizer_price_index_phosphate,oil_price,meat_total(kg/capita),meat_total_us(lb/capita),fruits(kg/capita),vegetable(kg/capita),coffee_us(gal/capita),...,population_world,population_asia_all,population_asia_east&southeast,cpi_us,gini_us,harvestedarea_rice_asia(ha),yield_rice_asia(hg/ha),production_rice_asia(ton),food_consumption_us(kcal),crop_price_us
0,1900-01,2.687540,9.292814,1.000000,7.483910,10.803852,80.945119,34.539159,11.243287,31.117215,...,3.129322e+05,5.641570e+04,9.666280e+04,8.664286,26.981158,8.572384e+07,5954.000000,6.884081e+07,3007.102825,106.0
1,1900-02,2.701685,9.297349,1.000000,7.483910,10.803852,80.945119,34.539159,11.243287,31.117215,...,3.165401e+05,5.859826e+04,9.788104e+04,8.671429,26.991586,8.576468e+07,5971.000000,6.884081e+07,3007.738058,106.0
2,1900-03,2.715830,9.301883,1.000000,7.483910,10.803852,80.945119,34.539159,11.243287,31.117215,...,3.201480e+05,6.078082e+04,9.909929e+04,8.678571,27.002013,8.580553e+07,5988.000000,6.884081e+07,3008.373292,106.0
3,1900-04,2.729975,9.306417,1.000000,7.483910,10.803852,80.945119,34.539159,11.243287,31.117215,...,3.237559e+05,6.296338e+04,1.003175e+05,8.685714,27.012441,8.584637e+07,6005.000000,6.884081e+07,3009.008525,106.0
4,1900-05,2.744120,9.310951,1.000000,7.483910,10.803852,80.945119,34.539159,11.243287,31.117215,...,3.273638e+05,6.514595e+04,1.015358e+05,8.692857,27.022868,8.588721e+07,6022.000000,6.884081e+07,3009.643758,106.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,2022-08,84.669442,85.799127,76.915370,319.321114,50.831212,196.200895,85.911032,99.962722,28.765632,...,7.980680e+06,4.725014e+06,2.344734e+06,296.171000,42.320014,1.458053e+08,49736.511905,7.063983e+08,3941.531195,1074.0
1472,2022-09,84.784497,85.918256,77.023596,319.610231,50.831212,196.200895,85.911032,99.962722,28.765632,...,7.986254e+06,4.727392e+06,2.345143e+06,296.808000,42.330441,1.458461e+08,49770.705357,7.070261e+08,3942.166428,1074.0
1473,2022-10,84.899552,86.037386,77.131823,319.899347,50.831212,196.200895,85.911032,99.962722,28.765632,...,7.991829e+06,4.729771e+06,2.345551e+06,298.012000,42.340869,1.458870e+08,49804.898810,7.076538e+08,3942.801662,1074.0
1474,2022-11,85.014608,86.156516,77.240050,320.188464,50.831212,196.200895,85.911032,99.962722,28.765632,...,7.997403e+06,4.732150e+06,2.345960e+06,297.711000,42.351296,1.459278e+08,49839.092262,7.082816e+08,3943.436895,1074.0
1475,2022-12,85.129663,86.275646,77.348277,320.477580,50.831212,196.200895,85.911032,99.962722,28.765632,...,8.002978e+06,4.734529e+06,2.346369e+06,296.797000,42.361724,1.459686e+08,49873.285714,7.089093e+08,3944.072129,1074.0

Add Gaussian Noise

In [17]:
ds_aug = pd.DataFrame(columns=ds.columns)

for state in ds['state'].unique():
    df = ds[ds['state'] == state]

    for index, row in df.iterrows():
        string_labels = ['ID', 'state', 'crop']
        new_rows = list()
        name_list = list()
        columns_list = list()

        ym_split = row['ID'].split('-')
        num_make = monthrange(*[int(x) for x in ym_split])[1]

        for column in df:
            if column in string_labels:
                name_list.append(row[column])
                continue

            try:
                std_original = df[column].std()
                std_noise = math.sqrt(std_original)
                if std_noise > std_original:
                    std_noise = std_original

                noise = np.random.normal(row[column], std_noise, num_make)
                new_rows.append(noise)
                columns_list.append(column)

            except TypeError:
                pass

        df_append = pd.DataFrame(data=np.array(new_rows).T, columns=columns_list)
        for column, name in zip(string_labels, name_list):
            df_append[column] = name
        df_append['ID'] = df_append['ID'] + '-' + (df_append.index + 1).map(str).str.zfill(2)
        
        ds_aug = pd.concat([ds_aug, df_append], ignore_index=True)

In [18]:
ds_aug

,ID,state,temperature_avg,CDD,GDD,HDD,temperature_max,temperature_min,precipitation,snow_depth,snow_fall,sunlight_svm,sunlight_reg,crop,productions_spring,harvested_spring,cultivated_spring,productions_winter,harvested_winter,cultivated_winter
0,1900-01-01,AR,47.397000,-3.608095,67.387693,640.280360,63.100440,12.207964,5.457197,1.167841,3.544898,142.760631,154.854483,Rice,422805.664808,324769.993990,326199.602722,NaN,NaN,NaN
1,1900-01-02,AR,43.217359,9.396590,38.355738,636.911402,70.696219,11.658630,1.844281,1.991245,3.131038,139.601030,141.126873,Rice,419753.913790,325238.422078,326606.023230,NaN,NaN,NaN
2,1900-01-03,AR,45.222370,-2.128486,54.183592,631.785891,66.363806,11.669959,1.720686,3.239415,4.130902,144.092336,129.377885,Rice,422301.909500,325835.633775,325338.606271,NaN,NaN,NaN
3,1900-01-04,AR,48.805899,1.838934,39.463261,661.690864,69.109902,16.332547,-0.075040,0.038753,4.015017,133.976914,145.031122,Rice,421572.647710,325937.022876,325206.049243,NaN,NaN,NaN
4,1900-01-05,AR,39.235538,-1.248180,78.132346,629.973892,70.991284,9.727979,2.337733,0.533979,1.212623,135.638305,143.916461,Rice,422049.684464,325705.925772,327118.430522,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404320,2022-12-27,SD,11.738507,-15.453469,5.225019,1640.212245,35.477295,-20.807978,0.824947,11.317485,18.445158,126.564013,160.045601,Wheat,700722.519580,19522.555494,26465.011977,1.034281e+06,729306.667602,831033.278144
404321,2022-12-28,SD,12.200513,-8.735361,-15.256639,1677.686965,44.230097,-14.620599,1.927956,13.092477,18.318761,128.862388,148.230898,Wheat,699855.713412,19540.565598,26490.985807,1.034097e+06,731152.603342,829921.051137
404322,2022-12-29,SD,11.825465,4.317241,-3.129975,1664.403184,47.541533,-18.595721,2.005343,8.775622,15.551083,155.335856,159.044525,Wheat,700332.506522,19472.227274,25984.837972,1.032827e+06,730311.569872,830160.015213
404323,2022-12-30,SD,11.633764,1.399030,-18.441212,1661.553670,43.675210,-14.040687,1.781570,7.939719,16.690407,155.832523,165.420191,Wheat,700590.371867,19868.609249,26472.389889,1.032787e+06,729350.722834,830551.959716
404324,2022-12-31,SD,21.994864,11.597869,20.884432,1672.327494,42.364145,-19.574962,2.210157,10.576904,11.515227,129.898633,138.845881,Wheat,700544.647681,19673.774769,26798.695403,1.033378e+06,730848.118655,829939.217123

In [19]:
da_aug = pd.DataFrame(columns=da.columns)

for state in ['_']:
    df = da

    for index, row in df.iterrows():
        string_labels = ['ID']
        new_rows = list()
        name_list = list()
        columns_list = list()

        ym_split = row['ID'].split('-')
        num_make = monthrange(*[int(x) for x in ym_split])[1]

        for column in df:
            if column in string_labels:
                name_list.append(row[column])
                continue

            try:
                std_original = df[column].std()
                std_noise = math.sqrt(std_original)
                if std_noise > std_original:
                    std_noise = std_original

                noise = np.random.normal(row[column], std_noise, num_make)
                new_rows.append(noise)
                columns_list.append(column)

            except TypeError:
                pass

        df_append = pd.DataFrame(data=np.array(new_rows).T, columns=columns_list)
        for column, name in zip(string_labels, name_list):
            df_append[column] = name
        df_append['ID'] = df_append['ID'] + '-' + (df_append.index + 1).map(str).str.zfill(2)
        
        da_aug = pd.concat([da_aug, df_append], ignore_index=True)

In [20]:
da_aug

,ID,fertilizer_price_index_all,fertilizer_price_index_nitrogen,fertilizer_price_index_phosphate,oil_price,meat_total(kg/capita),meat_total_us(lb/capita),fruits(kg/capita),vegetable(kg/capita),coffee_us(gal/capita),...,population_world,population_asia_all,population_asia_east&southeast,cpi_us,gini_us,harvestedarea_rice_asia(ha),yield_rice_asia(hg/ha),production_rice_asia(ton),food_consumption_us(kcal),crop_price_us
0,1900-01-01,6.842481,17.591760,5.300159,-6.166868,5.701234,82.368400,36.388110,12.980564,30.362216,...,3.135210e+05,5.731157e+04,9.689851e+04,-8.887188,27.878423,8.572299e+07,5912.332609,6.883611e+07,3029.260559,123.207309
1,1900-01-02,3.464146,12.609040,-11.445294,2.345514,11.708261,94.102631,36.651436,8.705695,30.853207,...,3.117833e+05,5.523883e+04,9.649051e+04,13.938841,27.192529,8.572740e+07,5975.281010,6.886393e+07,2989.085149,94.584131
2,1900-01-03,2.546887,8.056872,4.517651,0.493567,11.246666,88.531426,40.932791,12.124716,26.484282,...,3.139343e+05,5.656076e+04,9.579785e+04,5.066021,28.284472,8.572413e+07,5728.099842,6.883985e+07,3008.604445,126.583751
3,1900-01-04,-0.117536,5.592678,-10.340355,25.981751,14.361671,81.238154,34.262136,13.679563,36.646016,...,3.145722e+05,5.723080e+04,9.576906e+04,2.357373,27.898179,8.572613e+07,5986.405033,6.880803e+07,3021.976155,110.368834
4,1900-01-05,4.198748,6.061925,1.721705,14.797951,9.882540,81.919420,36.339556,10.916261,31.701089,...,3.103508e+05,5.629474e+04,9.633940e+04,11.852832,28.146267,8.571782e+07,6184.239830,6.884078e+07,2983.934356,67.421036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44920,2022-12-27,82.989397,84.320938,77.988988,312.683572,46.724511,194.467468,76.691805,96.157125,23.244231,...,8.002121e+06,4.736593e+06,2.348196e+06,298.602383,42.288073,1.459672e+08,49759.043292,7.088908e+08,3909.640456,1087.758550
44921,2022-12-28,84.406468,81.970627,85.767782,325.909920,50.311717,197.935284,94.525848,99.215748,27.813612,...,8.002425e+06,4.736264e+06,2.345299e+06,302.136978,42.319733,1.459622e+08,49948.365416,7.089012e+08,3968.003455,1086.920539
44922,2022-12-29,77.672314,84.455823,85.516990,329.346039,48.279918,190.352178,88.941431,107.239116,31.350889,...,8.001537e+06,4.736058e+06,2.346068e+06,287.494378,42.965839,1.459691e+08,49803.812384,7.089068e+08,3925.677510,1065.022645
44923,2022-12-30,86.461322,87.886153,77.768554,314.867340,52.880410,196.733777,86.616442,101.100177,28.392726,...,8.003849e+06,4.733635e+06,2.346302e+06,284.064722,44.900120,1.459639e+08,49766.555748,7.089223e+08,3960.919680,1071.130294
44924,2022-12-31,84.432007,86.654161,82.567304,323.207557,48.367492,194.154965,79.296735,91.173860,33.217068,...,8.003259e+06,4.733595e+06,2.347404e+06,288.419288,43.200525,1.459640e+08,50034.067247,7.089002e+08,3931.648984,1084.773579

In [21]:
ds_aug.to_csv('./data_by_states_gaussiannoise.csv', index=False)
da_aug.to_csv('./data_by_all_gaussiannoise.csv', index=False)

Min-max Scailing

잡음을 넣어서 정상적인 Range를 벗어난 숫자값들이 있습니다. Scailing을 필수적으로 해주어야 합니다.

스케일링은 반드시 Train Set, Validation Set, Test Set 각각 별도로 해야 한다는 것 잊지 마세요! (여기 예제에서는 구분하지 않고 보여줍니다.)

In [22]:
scaler = MinMaxScaler()

former = ds_aug.loc[:, ['ID', 'state', 'crop']]
latter = ds_aug[ds_aug.columns.difference(['ID', 'state', 'crop'])]

fitted = scaler.fit(latter)
output_latter = scaler.transform(latter)
output_latter = pd.DataFrame(output_latter, columns=latter.columns, index=list(latter.index.values))
ds_minmax = pd.concat([former, output_latter], axis=1)

                ID state   crop       CDD       GDD       HDD  \
0       1900-01-01    AR   Rice  0.063957  0.101900  0.296726
1       1900-01-02    AR   Rice  0.078119  0.081186  0.295357
2       1900-01-03    AR   Rice  0.065568  0.092479  0.293276
3       1900-01-04    AR   Rice  0.069889  0.081976  0.305421
4       1900-01-05    AR   Rice  0.066527  0.109566  0.292540
...            ...   ...    ...       ...       ...       ...
404320  2022-12-27    SD  Wheat  0.051057  0.057548  0.702831
404321  2022-12-28    SD  Wheat  0.058373  0.042935  0.718050
404322  2022-12-29    SD  Wheat  0.072588  0.051587  0.712655
404323  2022-12-30    SD  Wheat  0.069410  0.040663  0.711498
404324  2022-12-31    SD  Wheat  0.080517  0.068721  0.715874

        cultivated_spring  cultivated_winter  harvested_spring  \
0                0.022154                NaN          0.022478
1                0.022183                NaN          0.022510
2                0.022095                NaN          0.022552
3                0.022085                NaN          0.022559
4                0.022218                NaN          0.022543
...                   ...                ...               ...
404320           0.001334           0.395488          0.001179
404321           0.001336           0.394960          0.001180
404322           0.001301           0.395073          0.001176
404323           0.001335           0.395260          0.001203
404324           0.001357           0.394968          0.001190

        harvested_winter  precipitation  productions_spring  \
0                    NaN       0.330147            0.005962
1                    NaN       0.226279            0.005918
2                    NaN       0.222725            0.005954
3                    NaN       0.171100            0.005944
4                    NaN       0.240465            0.005951
...                  ...            ...                 ...
404320          0.366585       0.196974            0.009942
404321          0.367519       0.228684            0.009930
404322          0.367093       0.230909            0.009936
404323          0.366608       0.224476            0.009940
404324          0.367365       0.236797            0.009939

        productions_winter  snow_depth  snow_fall  sunlight_reg  sunlight_svm  \
0                      NaN    0.199900   0.220057      0.330570      0.295316
1                      NaN    0.215717   0.213418      0.298584      0.287957
2                      NaN    0.239693   0.229456      0.271208      0.298418
3                      NaN    0.178211   0.227597      0.307681      0.274858
4                      NaN    0.187724   0.182648      0.305084      0.278727
...                    ...         ...        ...           ...           ...
404320            0.365146    0.394868   0.459053      0.342666      0.257592
404321            0.365081    0.428964   0.457025      0.315137      0.262945
404322            0.364632    0.346040   0.412632      0.340333      0.324606
404323            0.364618    0.329983   0.430907      0.355189      0.325763
404324            0.364827    0.380642   0.347898      0.293269      0.265359

        temperature_avg  temperature_max  temperature_min
0              0.559880         0.438514         0.487037
1              0.525199         0.502231         0.483251
2              0.541836         0.465889         0.483330
3              0.571571         0.488924         0.515460
4              0.492159         0.504706         0.469947
...                 ...              ...              ...
404320         0.263998         0.206798         0.259523
404321         0.267832         0.280221         0.302161
404322         0.264720         0.307999         0.274768
404323         0.263129         0.275566         0.306157
404324         0.349102         0.264568         0.268020

[404325 rows x 20 columns]

In [23]:
scaler = MinMaxScaler()

former = da_aug.loc[:, ['ID']]
latter = da_aug[da_aug.columns.difference(['ID'])]

fitted = scaler.fit(latter)
output_latter = scaler.transform(latter)
output_latter = pd.DataFrame(output_latter, columns=latter.columns, index=list(latter.index.values))
da_minmax = pd.concat([former, output_latter], axis=1)

               ID  co2(ppm)  cocoa_us(lb/capita)  coffee_us(gal/capita)  \
0      1900-01-01  0.052575             0.352417               0.462962
1      1900-01-02  0.157172             0.575605               0.474434
2      1900-01-03  0.102509             0.357460               0.372353
3      1900-01-04  0.047535             0.309568               0.609786
4      1900-01-05  0.111075             0.278344               0.494246
...           ...       ...                  ...                    ...
44920  2022-12-27  0.967661             0.694446               0.296648
44921  2022-12-28  0.950294             0.729149               0.403413
44922  2022-12-29  0.943287             0.606834               0.486063
44923  2022-12-30  0.932365             0.618908               0.416944
44924  2022-12-31  0.946243             0.660168               0.529667

         cpi_us  crop_price_us  fertilizer_price_index_all  \
0      0.055366       0.094971                    0.149101
1      0.120323       0.069044                    0.126970
2      0.095073       0.098029                    0.120961
3      0.087365       0.083342                    0.103507
4      0.114387       0.044439                    0.131783
...         ...            ...                         ...
44920  0.930407       0.968661                    0.647929
44921  0.940466       0.967902                    0.657212
44922  0.898797       0.948067                    0.613097
44923  0.889037       0.953599                    0.670673
44924  0.901429       0.965958                    0.657379

       fertilizer_price_index_nitrogen  fertilizer_price_index_phosphate  \
0                             0.206072                          0.146613
1                             0.168168                          0.046484
2                             0.133539                          0.141934
3                             0.114793                          0.053090
4                             0.118363                          0.125215
...                                ...                               ...
44920                         0.713692                          0.581255
44921                         0.695813                          0.627768
44922                         0.714718                          0.626269
44923                         0.740813                          0.579937
44924                         0.731441                          0.608631

       food_consumption_us(kcal)  ...  oil_price  population_asia_all  \
0                       0.049463  ...   0.052765             0.000804
1                       0.017893  ...   0.063459             0.000361
2                       0.033231  ...   0.061132             0.000643
3                       0.043739  ...   0.093152             0.000787
4                       0.013846  ...   0.079103             0.000587
...                          ...  ...        ...                  ...
44920                   0.741256  ...   0.453329             0.999908
44921                   0.787117  ...   0.469945             0.999837
44922                   0.753858  ...   0.474262             0.999793
44923                   0.781551  ...   0.456073             0.999276
44924                   0.758550  ...   0.466550             0.999268

       population_asia_east&southeast  population_us_asian  \
0                            0.000846             0.000378
1                            0.000665             0.000397
2                            0.000358             0.000173
3                            0.000345             0.000460
4                            0.000598             0.000444
...                               ...                  ...
44920                        0.999992             0.999756
44921                        0.998706             0.999883
44922                        0.999047             0.999781
44923                        0.999151             0.999988
44924                        0.999640             1.000000

       population_us_total  population_world  production_rice_asia(ton)  \
0                 0.000059          0.000440                   0.000084
1                 0.000067          0.000214                   0.000128
2                 0.000073          0.000494                   0.000090
3                 0.000127          0.000577                   0.000041
4                 0.000042          0.000028                   0.000092
...                    ...               ...                        ...
44920             0.981184          0.999566                   0.999916
44921             0.981124          0.999605                   0.999933
44922             0.981099          0.999490                   0.999942
44923             0.981046          0.999790                   0.999966
44924             0.981126          0.999714                   0.999931

       tea_us(gal/capita)  vegetable(kg/capita)  yield_rice_asia(hg/ha)
0                0.517142              0.174019                0.005261
1                0.738260              0.139412                0.006679
2                0.428672              0.167091                0.001111
3                0.440198              0.179678                0.006929
4                0.423510              0.157308                0.011386
...                   ...                   ...                     ...
44920            0.338626              0.847359                0.992990
44921            0.581204              0.872120                0.997254
44922            0.361096              0.937072                0.993998
44923            0.386909              0.887375                0.993159
44924            0.376299              0.807018                0.999185

[44925 rows x 25 columns]

In [24]:
ds_minmax.to_csv('./data_by_states_minmax.csv', index=False)
da_minmax.to_csv('./data_by_all_minmax.csv', index=False)

Scaler만 변경하면 정규분포 표준화도 똑같이 할 수 있습니다.

그런데 선형 관계에 있는 Feature가 많아서 선형적으로 분석해야 결과가 잘 나올 것이라고 생각합니다.